## Test implementation
----

In [1]:
from CBFW import CBFW
#from mdlpc import MDLP_Discretizer

import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [2]:
# read dataset
train = pd.read_csv('./data/monks-1.train', header=None, sep=' ')
X_train, y_train = train.iloc[:,2:-1], train.iloc[:,1]

test  = pd.read_csv('./data/monks-1.test', header=None, sep=' ')
X_test, y_test = test.iloc[:,2:-1], test.iloc[:,1]

In [3]:
model = CBFW()
model.fit(X_train, y_train)

In [4]:
model.NIAC

array([1.13083615, 0.09159897, 0.07328026, 0.39803344, 4.2920964 ,
       0.01415477])

In [5]:
model.NIAA

array([1.69030587, 1.20316308, 0.16337628, 1.13021295, 1.40030284,
       0.41263898])

In [6]:
model.W

array([0.36367017, 0.24757941, 0.47749122, 0.32471663, 0.94743927,
       0.40167658])

In [7]:
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.67      0.99      0.80       216
           1       0.97      0.51      0.67       216

    accuracy                           0.75       432
   macro avg       0.82      0.75      0.74       432
weighted avg       0.82      0.75      0.74       432



In [8]:
y_pred = model.predict(X_test, naive=True)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      0.76      0.73       216
           1       0.74      0.66      0.70       216

    accuracy                           0.71       432
   macro avg       0.72      0.71      0.71       432
weighted avg       0.72      0.71      0.71       432

